import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Landingpage</Link>
        </li>
        <li>
          <Link to="/frame2044">Frame2044</Link>
        </li>
        <li>
          <Link to="/frame2045">Frame2045</Link>
        </li>
        <li>
          <Link to="/frame2042">Frame2042</Link>
        </li>
        <li>
          <Link to="/frame2046">Frame2046</Link>
        </li>
        <li>
          <Link to="/frame2043">Frame2043</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
